import type { Metadata } from 'next';

import AppHeader from '@/components/AppHeader/AppHeader';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Food App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
